ignore:
  - zenhub/_version.py
  - '*tests*'
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%  # PR will fail if it drops coverage on the project by >1%
    patch:
      default:
        target: auto
        threshold: 40%  # A given PR will fail if >40% is untested
comment:
  require_changes: true # if true: only post the PR comment if coverage changes
