[tool.black]
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = true
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
skip_glob = []

[tool.mypy]
files = "zenhub"
ignore_missing_imports = true
exclude = [
  "tests",
]
show_error_codes = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true
# disallow_any_generics = true
