name: PR Test

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install napari
        run: pip install -e .
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit
        env:
          ZENHUB_TEST_TOKEN:  ${{ secrets.ZENHUB_TEST_TOKEN }}
        run: pre-commit run -a

  check-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install napari
        run: pip install -e .
      - name: Install dependencies
        run: pip install check-manifest
      - name: Run check
        run: check-manifest

  test:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install napari
        run: pip install -e .
      - name: Install dependencies
        run: pip install pytest pytest-cov
      - name: Run pytest
        env:
          ZENHUB_TEST_TOKEN:  ${{ secrets.ZENHUB_TEST_TOKEN }}
        run: pytest tests --cov=zenhub
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
